name: transmission

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "apps/transmission/**"

jobs:
  images-build:
    uses: kien-truong/containers/.github/workflows/collect-image-metadata.yml@main
    with:
      path: apps/transmission
    secrets: inherit
