name: transmission

on:
  workflow_dispatch:
    inputs:
      image-refresh:
        type: boolean
  workflow_run:
    workflows:
      - ubuntu
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "apps/transmission/metadata.json"
      - "apps/transmission/revision.json"

jobs:
  build-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      path: apps/transmission
      image-refresh: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.image-refresh)}}
    secrets: inherit
