name: transmission

on:
  workflow_dispatch:
  schedule:
    - cron: '40 3 * * 0'
  push:
    branches:
      - main
    paths:
      - "apps/transmission/revision.json"

jobs:
  build-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      path: apps/transmission
      schedule: ${{ github.event.schedule }}
    secrets: inherit
