name: transmission

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/transmission/revision.json"

jobs:
  images-build:
    uses: kien-truong/containers/.github/workflows/collect-image-metadata.yml@main
    with:
      path: apps/transmission
    secrets: inherit
