name: transmission

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows:
  #     - ubuntu
  #   types:
  #     - completed
  push:
    branches:
      - main
    paths:
      - "apps/transmission/metadata.json"
      - "apps/transmission/revision.json"

jobs:
  build-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      path: apps/transmission
      image-refresh: ${{ github.event_name == 'workflow_run' }}
    secrets: inherit
