name: ubuntu-base

on:
  push:
    branches:
      - main
    paths:
      - "bases/ubuntu/**"

jobs:
  read-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read metadata
        shell: bash
        run: |
          NAME=$(jq ".name" bases/ubuntu/metadata.json)
          echo "NAME=${NAME}" >> $GITHUB_OUTPUT

          PLATFORMS=$(jq ".platforms" bases/ubuntu/metadata.json)
          echo "PLATFORMS=${PLATFORMS}" >> $GITHUB_OUTPUT

          VERSIONS=$(jq ".versions" bases/ubuntu/metadata.json)
          echo "VERSIONS=${VERSIONS}" >> $GITHUB_OUTPUT

  images-build:
    needs:
      - read-metadata
    uses: kien-truong/containers/.github/workflows/build-image.yml@main
    with:
      name: "${{ needs.read-metadata.outputs.NAME }}"
      versions: "${{ needs.read-metadata.outputs.VERSIONS }}"
      platforms: "${{ needs.read-metadata.outputs.PLATFORMS }}"
      path: "bases/ubuntu/Dockerfile"
    secrets: inherit
