name: ubuntu

on:
  workflow_dispatch:
    inputs:
      image-refresh:
        type: boolean
  schedule:
    - cron: '40 3 * * 0'
  push:
    branches:
      - main
    paths:
      - "bases/ubuntu/metadata.json"
      - "bases/ubuntu/revision.json"

jobs:
  build-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      path: bases/ubuntu
      image-refresh: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.image-refresh)}}
    secrets: inherit
