name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "bases/ubuntu/**"

jobs:
  images-build:
    uses: kien-truong/containers/.github/workflows/collect-image-metadata.yml@main
    with:
      path: bases/ubuntu
    secrets: inherit
