name: ubuntu

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "bases/ubuntu/**"

jobs:
  read-metadata:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.meta.outputs.name }}
      versions: ${{ steps.meta.outputs.versions }}
      platforms: ${{ steps.meta.outputs.platforms }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Read metadata
        id: meta
        shell: bash
        run: |
          NAME=$(jq -r -c ".name" bases/ubuntu/metadata.json)
          echo "name=${NAME}" >> $GITHUB_OUTPUT

          PLATFORMS=$(jq -c '.platforms | join(",")' bases/ubuntu/metadata.json)
          echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT

          VERSIONS=$(jq -r -c ".versions" bases/ubuntu/metadata.json)
          echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT

  images-build:
    needs:
      - read-metadata
    uses: kien-truong/containers/.github/workflows/build-image.yml@main
    with:
      name: ${{ needs.read-metadata.outputs.name }}
      versions: ${{ needs.read-metadata.outputs.versions }}
      platforms: ${{ needs.read-metadata.outputs.platforms }}
      path: bases/ubuntu/Dockerfile
    secrets: inherit
