name: ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bases/ubuntu/revision.json"

jobs:
  images-build:
    uses: kien-truong/containers/.github/workflows/collect-image-metadata.yml@main
    with:
      path: bases/ubuntu
    secrets: inherit
