name: ubuntu

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2 * * 0'
  push:
    branches:
      - main
    paths:
      - "bases/ubuntu/revision.json"

jobs:
  build-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      path: bases/ubuntu
      schedule: ${{ github.event.schedule }}
    secrets: inherit
